name: topiary
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numpy
  - pandas
  - xlrd
  - openpyxl
  - matplotlib
  - biopython
  - tqdm
  - ete3
  - dendropy
  - toytree
  - pastml
  #- openmpi  # [not win]
  #- blast    # [not win]
  #- muscle   # [not win]
  #- generax  # [not win]
  #- raxml-ng # [not win]
  #- mpi4py   # [not win]
  - pip
  - pip:
    - opentree
